### ISSUE TITLE
New Covid WF in lims

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/cglims#21]
A new workflow is being added to lims for covid samples.

- [x] build new wf on stage
- [x] create a test specification and get it approved
- [x] perform test
- [x] get the test approved
- [x] deploy new workflow on lims-prod

The issue can be closed when all points are chaecked.

**Comment by henrikstranneheim** [comment]
@mayabrandi Can we consider this done or do you want to wait for Cissis validation before closing it? I guess any modifications should be done in future separate issues?

**Comment by mayabrandi** [comment]
I think we should wait untill the new wf is in production. Sorry for not being more specific in the description.
