### ISSUE TITLE
Add a Planning for hyb step in TWIST wf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/cglims#23]
Lims Issue
---------------

**Work Flow:** TWIST v3
**Protocol:** Target Enrichment TWIST v2
**Step:** Pool samples for hybridization TWIST

**Description:** We would like to add a planning step before the step *Pool samples for hybridization TWIST*. 

From ALY:
"Due to different facts around the samples, we have to bring samples into a LIMS step, run a script, check if it is fine, if it is not, we have to remove all samples, start all over again, run the script, and we typically do this several times. The problem is that we cannot remove single samples from the step and and bring them back. The whole process takes a few hours which is a major problem."

In a meeting with ALY, MB, VK, OL and CS it was decided to, to reduce time spent on this we will add planning step before the actual pooling is done.

In the planning step it should be possible to write a pool name (at sample level) and run the script "Calculate Volumes" that is used in the step *Pool samples for hybridization TWIST*. It should also be possible to change the pooling name for samples and run the script again. It should also be possible to run the script *Make Pooling Map* to see why a sample or pool gets a red flag.

When done with the planning step it should be possible to choose the next step, either *Pool samples for hybridization TWIST* or repeat step (the planning).

The samples that are pushed forward to *Pool samples for hybridization TWIST* should have the UDF: "Pool name" that was added in the planning step, visible in the queue to the step.

**Comment by AnnaLeinfelt** [comment]
Hej @cesve! Är denna fortfarande aktuell? Jag tror att detta repo inte används och att issues ska läggas i cg_lims repot.

**Comment by cesve** [comment]
Det är den. Jag flyttar den!

**Comment by cesve** [comment]
Moved to cg_lims repo.

https://github.com/Clinical-Genomics/cg_lims/issues/92
